dxw/terraform-dxw-dalmatian-infrastructure

README.md
* The release badge is hosted from shields.io
=> Fix release badge URL

.terraform.lock.hcl, README.md, locals.tf, providers.tf, variables.tf, versions.tf
* Adds the project name, infrastructure name and environment variables to be used to create a resource prefix
* Adds the aws region variable, to determine which region the resources will be created
* Adds default tags
* Adds the AWS provider
=> Add initial variables, locals and provider

README.md, data.tf, kms-infrastructure.tf, locals.tf, policies/kms-key-policy-statements/root-allow-all.json.tpl, policies/kms-key-policy.json.tpl, variables.tf
* Enabling this feature creates a KMS key that can be used across all resources that support KMS encryption. Using a single KMS key can help reduce costs related to KMS. We can in future add a feature to use individual KMS keys for particular resources if needed.
=> Add infrastructure KMS key

vpc-infrastructure.tf
* This resource doesn't have a name parameter, and requires the 'Name' tag to be set so that it appears in the console - which makes it more human readable within the console
=> Add 'Name' tag to VPC

README.md, locals.tf, variables.tf, vpc-infrastructure-flow-logs-cloudwatch.tf, vpc-infrastructure-network-private.tf, vpc-infrastructure-network-public.tf
* This calculates the IP range for the 'private' and 'public' networks within the VPC. It does this by initially splitting the given vpc CIDR block into 2, and then calcalting the 'nebits' so that individual '/24' ranges can be calulated for subnets.
* A subnet for each given availability zone will be created, in both the 'private' and 'public' ranges.
* A public route table will be created, along with an Internet Gateway, and a 0/0 route created for the gateway. The subnets within the 'public' range will then be associated with this route table, allowing any resource launched within them to access the internet.
* A private route table will also be created. If 'public' networking is enabled, a NAT gateway will be created in one of the public subnets, and a route created to allow resources …
=> Create public and private networks

README.md, data.tf, locals.tf, providers.tf, route53-infrastructure.tf, variables.tf
* This allows creating Route53 Hosted Zones, with delegation (NS) records created in anoter (root) Route53 zone.
* To create the delegation records, an AWS profile name must be provided, and the current user must have access to read/write to that Route53 zone
* The Infrastructure Route53 zone will be used to hold DNS records for the resources launched.
=> Conditionally create Route53 Hosted Zone

.terraform.lock.hcl, README.md, data.tf, ec2-userdata/ecs-instance.tpl, ecs-cluster-infrastructure-draining-lambda.tf, ecs-cluster-infrastructure.tf, kms-infrastructure.tf, lambdas/ecs-ec2-draining/function.py, locals.tf, policies/ec2-ecs.json.tpl, policies/ecs-container-instance-state-update.json.tpl, policies/kms-encrypt.json.tpl, policies/kms-key-policy-statements/service-allow-encrypt.json.tpl, policies/kms-key-policy-statements/service-sns-allow-encrypt.json.tpl, policies/lambda-default.json.tpl, policies/sns-publish.json.tpl, variables.tf, versions.tf
* This will conditionally launch an ECS cluster within the infrastructure VPC. The EC2 instances within the ECS cluster do not need to be public (An ALB will be the public endpoint), but they can optionally be configured to be publicly available.
* A lifecycle hook has been added, which conditionally triggers a Lambda to ensure that all instances have drained their containers before terminating.
* The ECS instance type, ami version and docker storage parameters are configurable.
=> Create Infrastructure ECS cluster

ecs-cluster-infrastructure-draining-lambda.tf, ecs-cluster-infrastructure.tf, kms-infrastructure.tf
* `project_name` has been incorrectly used for resource names, it should be `resource_prefix`
=> Fix: Use `resource_prefix` instead of `project_name`

ecs-cluster-infrastructure-draining-lambda.tf, ecs-cluster-infrastructure.tf, vpc-infrastructure-flow-logs-cloudwatch.tf
* A role name can only be 64 characters
* This fix uses a hash of the role suffix instead of the full name, and then adds the full name as a description.
=> Fix: Role name lengths

ecs-cluster-infrastructure.tf
* Adds the list of enabled metrics for the ECS Cluster's autoscaling group. These are the metrics that are automatically enabled when choosing to enable metrics within the AWS console, which is also the full list of metrics avaiable for the autoscaling group.
=> Enable ECS Cluster autoscaling group metrics

README.md, ec2-userdata/ecs-instance.tpl, ecs-cluster-infrastructure.tf, efs-infrastructure.tf, locals.tf, variables.tf
* Conditionally creates an EFS file system. This can be used as a shared filesystem between the container instances.
* If the ECS cluster has been enabled, it will mount the EFS file system onto the instances at `/mnt/efs`
* A list of directories can be provided, which will be created within the EFS file system
* A security group is added that allows access from the ECS container instances security group. A rule is also added to the ECS container instances securit group to allow outbound to the EFS security group.
=> Conditionally create EFS for ECS cluster

.terraform.lock.hcl, README.md, data.tf, ecs-cluster-infrastructure.tf, external-data-scripts/get-ssm-service-setting.sh, locals.tf, policies/pass-role.json.tpl, policies/ssm-service-setting-rw.json.tpl, versions.tf
* This conditionally adds the policies with permissions required to use SSM default host management configuration.
* It checks for the value of the service setting to ensure dhcm has been enabled to decide wether to add the policies. `aws_ssm_service_setting` doesn't yet have a data source (https://github.com/hashicorp/terraform-provider-aws/issues/25170), so it uses a script along with the `external` provider instead to get the service setting parameters.
=> Conditionally add ECS cluster SSM policies

README.md, buildspecs/dalmatian-default.yml, ecs-cluster-infrastructure-service-build-ecr.tf, ecs-cluster-infrastructure-service-build-pipeline-codebuild.tf, policies/ecr-push.json.tpl
* Creates an ECR repository for each service defined
* Adds the steps to the default buildspec which logs into AWS ECR, and pushes the built image to the repository
=> CodePipeline CodeBuild push to ECR

ecs-cluster-infrastructure-service-cloudfront.tf
* `min_ttl`, `default_ttl` and `max_ttl` are managed by a cache policy (if specified). This fix prevents them being changed on every terraform deploy
=> Fix: Infrastructure service CloudFront TTLs

rds-infrastructure-password.tf
* Namespacing secrets in Secret Manager allows for an easier way to group secrets, for permissions and readability
=> Namespace RDS secret

README.md, appspecs/ecs.json.tpl, buildspecs/dalmatian-default.yml, ecs-cluster-infrastructure-service-alb.tf, ecs-cluster-infrastructure-service-build-pipeline-codebuild.tf, ecs-cluster-infrastructure-service-build-pipeline.tf, ecs-cluster-infrastructure-service-codedeploy-blue-green.tf, ecs-cluster-infrastructure-service-target-group.tf, ecs-cluster-infrastructure-service.tf, local-exec-scripts/create-codedeploy-deployment.sh, policies/codebuild-default.json.tpl, policies/codebuild-ecs-blue-green.json.tpl, policies/codepipeline-ecs-codedeploy.json.tpl, policies/ecs-codedeploy.json.tpl, versions.tf
* Allows setting the ECS deployment type to Blue/Green
* Creates a CodeDeploy App for the ECS service, and configures the CodeBuild project to create a new task defintion and appspec to deploy new revisions
* Runs a script to create a new deployment if the task defintion is updated in terraform
* If switching from "rolling" to "blue-green", the service must first be destroyed and recreated, due to the `ignore_changes` requirements for Blue/Green deployments (eg. service loadbalancer target groups)
=> ECS Service Blue/Green deployments

ecs-cluster-infrastructure-service-alb-global-accelerator.tf
* Has a max length of 64 chars, so need to use the resource prefix hash instead
=> Fix Global Accelerator name length

README.md, ecs-cluster-infrastructure-service-alb-global-accelerator.tf, route53-infrastructure.tf
* A non DUAL_STACK application load balancer cannot have a DUAL_STACK accelerator
=> Fix Global Accelerator IP address type

data.tf
* If the root domain is in another account, it needs to use the correct aliased provider for Route53
=> Fix root Route53 provider

efs-infrastructure.tf
* The subnet IDs can't be used as an index, as they aren't known until apply.
* This changes the for_each to use a map, with the resource index as the key
=> Fix EFS mount point for loop

ecs-cluster-infrastructure-service-alb.tf
* The host header values accepts a list, rather than individual strings
=> Fix dfomain names alb host headers

README.md, kms-infrastructure.tf, locals.tf, policies/kms-key-policy-statements/vpc-id-and-s3-bucket-allow.json.tpl, policies/s3-bucket-policy-statements/vpc-rw.json.tpl, ssm-documents/s3-download.json.tpl, ssm-documents/s3-upload.json.tpl, variables.tf, vpc-infrastructure-s3-transfer-ssm-documents.tf, vpc-infrastructure-s3-transfer.tf
* Creates an S3 bucket that can be accessed by resources within the VPC, and conditionally additional VPC ids.
* Creates SSM documents which can be used by the ECS cluster EC2 instances to upload and download objects from the transfer bucket.
=> Conditionally create transfer S3 bucket

ecs-cluster-infrastructure-service-alb.tf, ecs-cluster-infrastructure-service-codedeploy-blue-green.tf, ecs-cluster-infrastructure-service-target-group.tf, ecs-cluster-infrastructure-service.tf, route53-infrastructure.tf
* A container that doesn't require access (eg. worker containers), the container port is set to 0. These containers don't require target groups, or load balancer configuration in the code deploy app.
=> Fix container port 0

ecs-cluster-infrastructure-service-scheduled-task.tf
* The role index is the computed key, rather than the container name
=> Fix ECS scheduled task event target role arn

ecs-cluster-infrastructure-waf.tf
* Scope needs to be set to "CLOUDFRONT" (global) when associated to a CloudFront distribution
=> Fix CloudFront WAF ACL

README.md, ecs-cluster-infrastructure-service-alb.tf
* A listener rule is needed, rather than a listener per service, and the certificate subsequently associated with the listener.
=> Fix ALB certificates

ecs-cluster-infrastructure-service.tf
* Health check grace period is only valid for services configured to use load balancers
=> Fix ECS service grace period

ecs-cluster-infrastructure-draining-lambda.tf
* Name has a maximum length of 64, so use the resource prefix hash instead
=> Fix draining lambda name length

kms-infrastructure.tf
* The resource_prefix_hash is now being used for the name
=> Fix KMS key policy (draining lambda log group name)

ec2-userdata/ecs-instance.tpl
* Updating beyond the packages baked into the Amazon Linux is causing issues with the ecs-agent
=> Only do security updates with yum

ec2-userdata/ecs-instance.tpl
* The ecs service sometimes fails to start, if docker fails to start on first try. This adds `systemctl start ecs` to the end of ec2 userdata, to force start it.
=> Ensure the ecs service has started

data.tf
> Beginning with the June 12, 2024 releases of the Amazon ECS-optimized AMIs based on Amazon Linux 2, the default behavior will no longer include updating packages at launch. Instead, we recommend that you update to a new Amazon ECS-optimized AMI as releases are made available. The Amazon ECS-optimized AMIs are released when there are available security updates or base AMI changes. This will ensure you are receiving the latest package versions and security updates, and that the package versions are immutable through instance launches. For more information on retrieving the latest Amazon ECS-optimized AMI, see Retrieving Amazon ECS-optimized Linux AMI metadata.
* This changes the AMI from Amazon Linux 2 to Amazon Linux 2023
=> Upgrade to Amazon Linux 2023

rds-infrastructure-instance.tf
* If the resource prefix hash begins with a number, it fails to create the RDS, because the identifier must begin with a letter
* This change checks the first character of the hash, and if it is a number, it adds the letter 'h' to the beginning - For the RDS identifier only
=> Fix: RDS identifier must start with a letter

rds-infrastructure-instance.tf
* The regex checks for a string beginning with a number. Using the `regex` function, it will fail if there are no matches. To _test_ wether there are any matches, we need to use the `regexall` function, which produces a list of all matches - we then check the length of the result to see if there is a match.
=> Fix RDS identifier regex check

local-exec-scripts/create-codedeploy-deployment.sh
* The `create-codebuild-deployment.sh` script fails to create a new Deployment, if there is already one in progress.
* This adds in a check loop, and waits until any current Deployments are complete before attempting to create a new one.
=> Check for deployments in progress

ecs-cluster-infrastructure-service.tf
for loops dont use .value
```
╷
│ Error: Missing map element
│
│   on ecs-cluster-infrastructure-service.tf line 156, in resource "aws_ecs_task_definition" "infrastructure_ecs_cluster_service":
│  156:           containerPath = volume.value["container_path"]
│
│ This map does not have an element with the key "value".
```
=> Fix contaniner for loops

README.md, ecs-cluster-infrastructure-service-codedeploy-blue-green.tf
> The null_resource resource implements the standard resource lifecycle but takes no further action. On Terraform 1.4 and later, use the terraform_data resource type instead.
=> Replace null_resource with terraform_data

README.md, ecs-cluster-infrastructure-service-codedeploy-blue-green.tf, ecs-cluster-infrastructure-service.tf, local-exec-scripts/create-empty-s3-object.sh
* When a new service is deployed, if the .env file doesn't exist in the environment files S3 bucket, the initial deployment will fail and terraform stops
* This adds a script to create an empty .env file for the service, only if the file doesn't exist (It won't overwrite existing files). The script is then ran when the bucklet or service name changes
=> Create empty service env file

container-definitions/app.json.tpl, ecs-cluster-infrastructure-service-scheduled-task.tf, ecs-cluster-infrastructure-service.tf
* This allows adding environment variables using the app.json.tpl container defintion template
* We can then reuse this container definition for tasks that won't be using an S3 environment variable file (eg. passing in environment variables from Terraform)
=> Allow environment variables in app container definition

container-definitions/app.json.tpl, ecs-cluster-infrastructure-service-scheduled-task.tf, ecs-cluster-infrastructure-service.tf
* This allows using secrets rather than environment variables for containers. Using `secrets` allows environment variables to be set, but they will not be exposed within docker logs or inspect.
* We can use secrets to pass in sensitive environment variables such as database credentials.
=> Allow specifying secrets in app container definition

README.md, ecs-cluster-infrastructure-service-scheduled-task.tf, ecs-cluster-infrastructure.tf, policies/pass-role.json.tpl, rds-infrastructure-s3-backups-scheduled-task.tf
* Prevents needing to have multiple policies when more than 1 role needs to be passed to a service
=> Allow multiple role ARNs and Services in Pass Role policy

policies/kms-key-policy-statements/log-delivery-allow.json.tpl
* GenerateDataKey* and Decrypt* is required for all resources from the `delivery.logs.amazonaws.com` service, to allow CloudFront to use the KMS key
=> Fix log delivery KMS policy

README.md, ecs-cluster-infrastructure-service-cloudfront-logs-athena.tf, ecs-cluster-infrastructure-service-cloudfront-logs-glue-tables.tf, locals.tf
* Allows querying ECS Service CloudFront logs with Athena
* Creates an Athena workgroup, database and table with the columns required for CloudFront logs
=> Add CloudFront logs Athena and Glue tables

glue-table-schemas/cloudfront-logs.json.tpl, glue-table-schemas/vpc-flow-logs.json.tpl, locals.tf
* Stores the glue table schemas within files, rather than within locals.tf
* This allows them to be reused if needed, and keeps the locals.tf file tidier
=> Move glue table columns to json files

ecs-cluster-infrastructure-service-cloudfront-logs-athena.tf, locals.tf, vpc-infrastructure-flow-logs-athena.tf
* Changes the directory of the Athena result output, to consolidate them into a single directory within the logs bucket. This prevents multiple oddly named directories being created within the root of the bucket
=> Fix Athena result output location

.terraform.lock.hcl, README.md, buildspecs/dalmatian-datadog.yml, container-definitions/app.json.tpl, ecs-cluster-infrastructure-datadog-agent-api-key.tf, ecs-cluster-infrastructure-datadog-agent-ecr.tf, ecs-cluster-infrastructure-datadog-agent-image-codebuild.tf, ecs-cluster-infrastructure-datadog-agent-service.tf, ecs-cluster-infrastructure-logspout-service.tf, ecs-cluster-infrastructure-service-datadog-definition.tf, ecs-cluster-infrastructure-service-scheduled-task.tf, ecs-cluster-infrastructure-service.tf, kms-infrastructure.tf, locals.tf, providers.tf, rds-infrastructure-s3-backups-task-definition.tf, variables.tf, versions.tf
* Adds the datadog provider
* Conditionally launch a Datadog Agent in the ECS cluster
=> Datadog integration

README.md, ecs-cluster-infrastructure-instance-refresh-lambda.tf, kms-infrastructure.tf, lambdas/ecs-asg-instance-refresh/function.py, locals.tf, variables.tf
* Conditionally launch a Lambda which triggers an instance refresh on the ECS AutoScaling group, on a given Schedule Expression
* This is useful if the `max_instance_lifetime` causes the instances to refresh during a time that isn't optimal. The schedule expression could be set to run during out of hours
* Arguably this could be used in place of `max_instance_lifetime`, but would be good to have that as a backup aswell
=> ASG Instance Refresh Lambda

README.md, data.tf, ecs-cluster-infrastructure-instance-refresh-lambda.tf, ecs-cluster-infrastructure.tf, lambdas/ecs-asg-instance-refresh/function.py, locals.tf, policies/ec2-modify-launch-template.json.tpl
* Modifies the Lambda that triggers an instance refresh, to first update the image ID to the latest AMI. This ensures the instances will be using the most up to date AMI
* This has been placed within the instance refresh lambda, because it will require an instance refresh anyway to actually update the instances, and allows it to happen at the chosen instance refresh cron
* The AutoScaling group's launch template version has also been changed to '$Latest', rather than a specific version so that we don't need to keep that up to date with the latest version
=> Update image ID in launch template with instance refresh

s3-custom-buckets-cloudfront.tf
* We only want to use a default certificate if there is neither an infrastructure wildcard certifcate, or specified certificate ARN
=> Fix custom S3 bucket default certificate condition

data.tf
* An oddity with AWS naming - The managed caching policies all being with 'Managed-' except the polcies that begin with the word 'Use' ...
```
aws cloudfront list-cache-policies --query "CachePolicyList.Items[*].{Name:CachePolicy.CachePolicyConfig.Name, Id:CachePolicy.Id}"
```
=> Fix CloudFront managed caching policy naming

rds-infrastructure-cluster.tf
* The RDS identifiers must begin with a letter, but the resource prefix hash might begin with a number
* This has been fixed in the RDS instance - https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/blob/main/rds-infrastructure-instance.tf#L6
=> Fix RDS cluster identifier

rds-infrastructure-tooling-task-definition.tf
* The naming convention is `infrastructure-rds-tools`. This changes the name of the task definition so it complies ...
=> Fix RDS Tooling task definition name

README.md, rds-infrastructure-tooling-task-iam.tf
* The ECS Exec feature requires a task IAM role to grant containers the permissions needed for communication between the managed SSM agent (execute-command agent) and the SSM service
* This adds the `ssm-create-channels` to the RDS Tooling ECS task role
=> Fix: Add SSM Create channels policy to RDS Tooling task role

README.md, rds-infrastructure-tooling-task-iam.tf
* When using ECS Exec on a container, the cluster is configured to send the access logs to the logging S3 bucket (which is encrypted with KMS)
* This adds the required permissions to the 'rds-tooling' task role, to allow it to send the logs to the S3 bucket
=> Fix: Add S3 logging and KMS permissions to RDS tooling ECS task role

rds-infrastructure-tooling-task-definition.tf
* The managed RDS password secret stores the values as a JSON string: ``` {"username":"root","password":"<redacted>"} ``` To retrieve the `password`, we can just append `:password` to the ARN
* This modifies the `valueFrom` in the task definition to retrieve the password, rather than the full JSON string
=> Fix: Reference RDS `password` key from secret

README.md, rds-infrastructure-cluster.tf, rds-infrastructure-instance.tf, rds-infrastructure-tooling-task-iam.tf
* If the RDS is configured to use a dedicated KMS key, we have configured it so that the same key is used to encrypt the RDS Secret Value for the password.
* This adds a policy to the task execution role to allow decrypting with the KMS key
* This change also adds the infrastructure KMS key as the encryption key if the RDS is not configured to use a dedicated KMS key
=> Fix: RDS tooling role requires KMS decrypt

ecs-cluster-infrastructure-service-build-pipeline-s3-artifact-store.tf, s3-custom-buckets.tf, s3-infrastructure-logs.tf
* A warning is thrown if a filter is not set: 
``` │ Warning: Invalid Attribute Combination │
│   with aws_s3_bucket_lifecycle_configuration.infrastructure_ecs_cluster_service_build_pipeline_artifact_store,
│   on ecs-cluster-infrastructure-service-build-pipeline-s3-artifact-store.tf line 79, in resource "aws_s3_bucket_lifecycle_configuration" "infrastructure_ecs_cluster_service_build_pipeline_artifact_store":
│   79: resource "aws_s3_bucket_lifecycle_configuration" "infrastructure_ecs_cluster_service_build_pipeline_artifact_store" {
│
│ No attribute specified when one (and only one) of [rule[0].filter,rule[0].prefix] is required
│
│ This will be an error in a future version of the provider
│
│ (and one more similar warning elsewhere)
╵
```
* …
=> Add empty filter to S3 lifecycle rules

kms-infrastructure.tf
* The VPC transfer bucket can only be referenced if it has been enabled
=> Fix VPC transfer buket KMS policy

s3-custom-buckets-cloudfront.tf
* Fixes the condition, so that the default certificate is only used if one hasn't been provided.
* It was attempting to set the `cloudfront_default_certificate` to true, if it was using the infrastructure wildcard certificate - which just adds a 1 minute delay to every deploy (because CloudFront correctly doesn't set it to `true`, but silently fails)
=> Fix custom S3 bucket cloudfront certificate
